### ISSUE TITLE
1 fan ok and the other are off

### ISSUE THREAD

**Issue by s7relok** [bobrown101/linux-corsair-lighting-node-core-control#4]
Hello,

I installed the program, but I have bug.

I have lightning core pro. All 3 fan leds are working (tested before installing on windows)

But when I want to set some parameters, it applies to only one fan (the one connected at the port 1 of the hub and the led of the 2 other are off

here is the command in /usr/bin/computer-lights

sudo yarn start --numberFans 3 --colors red yellow green --animation SCROLL_REVERSE --period 100 --brightness 100

**Comment by s7relok** [comment]
I now have 2 working with 

sudo yarn start --numberFans 3 --ledsPerFan 34 --colors red yellow green --animation CIRCLE --period 100 --brightness 100
Fans : Corsair QL120

**Comment by bobrown101** [comment]
Hmm, my suggest was going to be to increase the --ledsPerFan count to 34 as corsairs website says that model has 34 leds (https://www.corsair.com/us/en/Categories/Products/Fans/RGB-%26-LED-Fans/iCUE-QL-RGB-PWM-Fan/p/CO-9050097-WW). However you just said you did that. I am more than welcome to help debug this in order to get it working for you but it makes it difficult if I don't have that fan model.

My suggestion would be to change to the following command:
`sudo yarn start --numberFans 3 --ledsPerFan 8 --colors white white white --animation STATIC`
And then slowly start to increase --ledsPerFan and record how to leds react. This information might be able to help me debug it.

**Comment by s7relok** [comment]
Tried some values, even 350 or 1000 and there's only 2 fans working

Tried to play with numberFans, it works for 1 and 2 only.

3 gives me 2 lighted fans

**Comment by s7relok** [comment]
I could use some wireshark in order to capture something while I'm playing with iCue.

What will you need?

**Comment by bobrown101** [comment]
I created a branch named 'debug' that will log out all packets its sending out.
My current theory is that somehow the packets are being truncated for being too long.

Could you run the following and send me maybe the first 100 lines of the output?
```
git clone https://github.com/bobrown101/linux-corsair-lighting-node-core-control.git
git checkout debug
yarn
sudo yarn start --numberFans 3 --ledsPerFan 34 --colors red green blue --animation STATIC --period 1000 --brightness 100
```

And then also run wireshark in the background and compare the packets the program is logging, vs the packets that are being picked up by wireshark

**Comment by s7relok** [comment]
There's an error and nothing launches

yarn run v1.22.0
$ ts-node index.ts --numberFans 3 --ledsPerFan 34 --colors red green blue --animation STATIC --period 1000 --brightness 100

/etc/linux-corsair-lighting-node-core-control/node_modules/usb/usb.js:159
                        if (error) return callback(error);
                     ^
TypeError: Cannot read property 'toString' of undefined
    at /etc/linux-corsair-lighting-node-core-control/controller.ts:33:14
    at Device.<anonymous> (/etc/linux-corsair-lighting-node-core-control/node_modules/usb/usb.js:159:22)
    at Transfer.<anonymous> (/etc/linux-corsair-lighting-node-core-control/node_modules/usb/usb.js:131:15)
error Command failed with exit code 1.
